name: Publish Docker image

on:
  workflow_dispatch:
  push:
    paths:
      - "versions.json"
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to docker hub
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, ' bump versions ') || github.event_name == 'workflow_dispatch' }}

    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest release tag name
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        id: get-latest-release
        with:
          repository: ${{ github.repository }}

      - name: Set image tag and description
        id: tag
        run: |
          echo "description=Using $(jq -r 'to_entries | map("\(.key): \(.value)") | join(" - ")' versions.json)" >> $GITHUB_OUTPUT

      - name: Build Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.get-latest-release.outputs.release }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.get-latest-release.outputs.release }}
          labels: |
            org.opencontainers.image.description=${{ steps.tag.outputs.description }}

      - name: Test
        run: |
          curl -s -L -O "https://github.com/IDPF/epub3-samples/releases/download/20170606/trees.epub"
          echo "Running test script..."
          sudo chown 1000:1000 .
          docker run --rm -v "$(pwd):/app:rw" --entrypoint="bash" ${{ github.repository }}:latest -c "./test.sh trees.epub"

      - name: Push Docker images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.get-latest-release.outputs.release }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.get-latest-release.outputs.release }}
          labels: |
            org.opencontainers.image.description=${{ steps.tag.outputs.description }}
